### ISSUE TITLE
"Add from template" not working

### ISSUE THREAD

**Issue by novakp79** [madmaxoft/SkauTan#140] opened 2018-06-01 13:46 UTC
The 2018/06/01 32-bit version does nothing after selecting a template from the "Add from template" menu. The main playlist screen shows only the Quickplayer menu, but the Quickplayer button itself is missing.
![image](https://user-images.githubusercontent.com/32485271/40843927-e0eddb12-65b2-11e8-9398-08161b7a1a72.png)

**Comment by madmaxoft** [comment] 2018-06-01 18:26
This is actually a UI failure after #135 (combined with bad splitter saving) - the quickplayer is only half of the main window, the other half is "hiding" below a splitter (between the "Start Playing Immediately" checkbox and the waveform display), just pull the splitter up and you'll have the playlist again.

The cause for this was fixed in e1ad65dedd37034e5b762e0aead6ad2b8ac8edb2 so it won't happen for new installs, but old installs need to pull the splitter manually.

**Closed by madmaxoft** 2018-06-01 18:26 UTC

**Comment by madmaxoft** [comment] 2018-06-01 20:36
I've added an additional fix for this that *should* fix things even for old installs.
